### ISSUE TITLE
Window is not defined with next js.

### ISSUE THREAD

**Issue by mctang719** [React95/React95#218]
Error message: 
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/user/Workspace/NextPlayground/my-website/node_modules/@react95/clippy/cjs/ClippyProvider.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/kristiforbes/Workspace/NextPlayground/my-website/node_modules/@react95/clippy/cjs/index.js:29:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///@react95/clippy:1:18)
    at Object.@react95/clippy (/Users/kristiforbes/Workspace/NextPlayground/my-website/.next/server/pages/index.js:967:1)
```
I tried with dynamic import and other methods to get around the issue, but none of them worked. 

Fix I did to get around was to delete this line: 
React95/packages/clippy/src/ClippyProvider.jsx:9 
`window.CLIPPY_CDN = '//s3.amazonaws.com/clippy.js/Agents/';`

I don't see any usage of this CLIPPY CDN. if it is safe to delete, this would be great. Thanks.

**Comment by ggdaltoso** [comment]
Hi @mctang719 !

Seems to be an easy fix!

Would you like to contribute?

**Comment by mctang719** [comment]
I would love to submit a pull request after getting the permission. Just one thing about deleting that line is it seems to be used in clippy js. Not sure if there’s any side effect of doing so. Thanks

**Comment by ggdaltoso** [comment]
@react95/clippy uses [clippyjs](https://github.com/pi0/clippyjs) under the hood and I think we are good to go with your suggestion. 

Clippyjs already handles the assets trough GitHub CDN in a pretty good way, inside the [`load` function](https://github.com/pi0/clippyjs/blob/master/lib/load.js#L6)

Also, the GitHub CDN is faster:
| GitHub CDN | AWS S3  |
|-------------|----------|
| ![GitHubCDN](https://user-images.githubusercontent.com/6536985/105072418-8cc6cb80-5a64-11eb-865b-3f50a35a4a6a.png) | ![S3](https://user-images.githubusercontent.com/6536985/105072437-93edd980-5a64-11eb-9697-635dbd802e32.png) |

So, I'm waiting for your contribution!

**Comment by mctang719** [comment]
I think I still need the permission to be able to push to a remote branch and submit a PR.

**Comment by ggdaltoso** [comment]
I've sent you an invitation for our [Gitter](https://gitter.im/React95/React95). 

Could we, please, talk in there?
